name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write      
  id-token: write 

jobs:
  deploy:
    
    name: Deploy to GitHub Pages
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build
    
      - name: Upload Artifact  
        uses: actions/upload-artifact@v1
        with:
            name: artifact
            path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            artifact_name: artifact
          